# Inverse kinematics
This notebook considers the problem of inverse kinematics, ie solving at each control cycle of the robot a quadratic program from the derivatives (jacobian) of the current state. It introduces the basic function to compute the Jacobians of the robot, and how to use them to compute an inverse-kinematics control law. One of the key difficulties is to understand in which frames each quantities is computed (might be in the world frame, in the local frame attached to the end effector, in some arbitrary goal frame, etc), as we should never mixed quantities expressed in different frames without transporting them in the right frame. 


## Set up
We will use a Gepetto-viewer, and the linear algebra of NumPy.

In [1]:
import pinocchio as pin
import numpy as np
import time
from numpy.linalg import pinv,inv,norm,svd,eig
from utils.tiago_loader import loadTiago
import matplotlib.pylab as plt; plt.ion()
from utils.meshcat_viewer_wrapper import MeshcatVisualizer

We will use the Tiago robot (https://youtu.be/6BwRqwD066g). This mobile manipulator from PAL Robotics:
- has a mobile basis which can move in the plane (3 dof)
- a manipulator arm (7 dof)
- a head (2 dof) both mounted on a prismatic axis moving vertically (1 dof).

This makes 
- 3 dof for the basis
- 9 dof for the body.

It also has 2 extra joints tot figure the wheels, which are not very useful for this notebook. 

The wheels and the basis rotations are represented by the cos and sin of the angle.
The size of the configuration vector is then 18, while the velocity vector has dimension 15.

A load function is available to make it easy to load the robot.

In [2]:
robot = loadTiago()
viz = MeshcatVisualizer(robot)


You can open the visualizer by visiting the following URL:
http://127.0.0.1:7001/static/


In [ ]:
# viz.viewer.jupyter_cell()

The configuration is represented by a vector of larger dimension, subject to constraints ( e.g. $cos^2+sin^2=1$).

It is not possible to randomly sample a configuration vector q, as these constraints should be respected.

Similarly, we should take care when integrating a velocity as summing a configuration q with a velocity v will not work (dimensions do not match).

Two functions in Pinocchio implements these functionnalities.

In [3]:
print(f"Velocity vector has {robot.model.nv} components")

Velocity vector has 15 components


In [19]:
np.random.seed(47)
q = pin.randomConfiguration(robot.model)
vq = np.random.rand(robot.model.nv)*2 - 1
DT = 1e-3
qnext = pin.integrate(robot.model, q, vq*DT)

A simple example moving the robot in the viewer following a constant (random) velocity is as follows.

In [20]:
for t in range(1000):
    q = pin.integrate(robot.model,q,vq*DT)
    viz.display(q)
    time.sleep(DT/10)

The robot is mobile, hence the camera view in the viewer is not always centered. 

## Forward kinematics and Jacobian

- We recall first the basic method to compute the robot forward kinematics.

We will consider two frames of interest on the robot: 
- the first one, named <tool> is at the tip of the end-effector
- the second one, named <basis>, is on the front of the robot basis, 10 cm above the ground.

Both are represented in Gepetto-Viewer by a frame composed of three RGB arrows. 

![](figures/frames_of_interest.png)

In [21]:
IDX_TOOL = robot.model.getFrameId('frametool')
IDX_BASIS = robot.model.getFrameId('framebasis')

In [22]:
# for i in range(79):
#     print( robot.model.frames[i])
robot.model.frames[IDX_TOOL]
# I=quadratic moment of the mesh, m = mass

Frame name: frametool paired to (parent joint/ previous frame)(9/52)
with relative placement wrt parent joint:
  R =
1 0 0
0 1 0
0 0 1
  p =    0    0 0.08
containing inertia:
  m = 0
  c = 0 0 0
  I = 
0 0 0
0 0 0
0 0 0

`model.frame` contains a relative placement ($SE(3)$) to a parent frame which will be a joint frame (aka a principal frame). It also contains dynamic constant if it is a representing a link (aka associated to a mesh).

### Computing frame placement
The global placement of the frames are computed by the Pinocchio function framesForwardKinematics, whose results are stored in robot.data.oMf.


In [24]:
# First call the whole body algorithm
pin.framesForwardKinematics(robot.model,robot.data,q)
# Then get the position
oMtool = robot.data.oMf[IDX_TOOL]
oMbasis = robot.data.oMf[IDX_BASIS]

print("Tool placement:",oMtool) # instances of SE(3) object
print("Basis placement:",oMbasis)

Tool placement:   R =
  0.181285  -0.955133  -0.234215
  0.652153   0.295021  -0.698326
  0.736093 -0.0261479   0.676375
  p =  0.879595 -0.482558  0.570475

Basis placement:   R =
-0.991535  0.129837         0
-0.129837 -0.991535         0
        0         0         1
  p =   1.36521 -0.271082      0.15



In [25]:
oMtool.translation

array([ 0.87959506, -0.48255773,  0.57047496])

In [26]:
new_pos = pin.SE3()
new_pos.rotation = np.eye(3)
# new_pos.translation = np.array([0., 0., 0.])
new_pos.translation = oMtool.translation
new_pos, oMtool
# new_pos
# oMtool.rotation = np.eye(3)

(  R =
 1 0 0
 0 1 0
 0 0 1
   p =  0.879595 -0.482558  0.570475,
   R =
   0.181285  -0.955133  -0.234215
   0.652153   0.295021  -0.698326
   0.736093 -0.0261479   0.676375
   p =  0.879595 -0.482558  0.570475)

In [27]:
# Place a cyan cylinder at the end of the effector, but without specific direction.
# Translation defines the referential point, no matter the rotation ... (translate first, rotate after)
name = f"world/cyl1"
radius = 0.05

viz.delete(name)
viz.addCylinder(name, 3*radius, radius/5, [0.,1.,1.,1])
viz.applyConfiguration(name,new_pos)

In [29]:
# Place a yellow cylinder at the end of the effector, just to make sure!
name = f"world/cyl2"
radius = 0.05
viz.delete(name)
viz.addCylinder(name, 3*radius, radius/5, [1.,1.,0.,1])
viz.applyConfiguration(name,oMtool)

It is very important to notice the instruction pattern (which is standard in all Pinocchio functions): 
- first call a whole-body algorithm (here *pin.framesForwardKinematics*)
- then access the results into *robot.data*.

`robot.model` refers to the structure and `robot.data` as container for data that are populated using a whole body algorithm for a given configuration on other elements.

The tool-placement matrix 
$^0M_{tool}$ represents the displacement 
from the world frame $F_0$ to the tool frame $F_{tool}$ express in $F_0$. 

It is this matrix that must be applied to vector express in $F_{tool}$ to transform it as vector express in $F_0$. 

It is composed on a rotation matrix $^0R_{tool}$ and a 3D vector $^0T_{tool}$: 

$^0M_{tool}= [^0R_{tool}, ^0T_{tool}]$, 

when $^0T_{tool}$ is the vector $o_{tool} - o_{0}$ from the origin of frame $F_0$ to the origin of from $F_{tool}$ expressed in the world frame $F_o$. 

$^0T_{tool} = $ `oMtool.translation`


We can also express $o_{tool} - o_{0}$ in the tool frame $F_{tool}$ by multiplying $^0T_{tool}$ by $^0R_{tool}^T$




![](figures/placement_SE3_object.png)

- Placed a yellow cylinder at the end of the effector using `oMtool`.
- Placed a cyan cyliner by setting the rotation to $Id(3)$. Note that the position stays the same, no matter the rotation. The cylinder is aligned with the world x axis. $[Id(3), ^0T_{tool}]$, 

> Take care to the multiplication operator in numpy. 
> The operator* is (unintuitively) mapped to the coefficient-wise multiplication ... i.e. not at all the matrix multiplication. You should use the operator @ to get the real matrix-matrix product. 
> Never mind, you will likely be tricked at least once by this design pattern.
> If you don't like it ... well there is nothing to do, this is the basic matrix library in Python, the world most used language. 

### Computing Jacobians
The jacobian of a frame of the robot is computed using `pin.computeFrameJacobian`

In [30]:
Jtool = pin.computeFrameJacobian(robot.model,robot.data,q,IDX_TOOL)
Jtool.shape

(6, 15)

This matrix has 6 rows and NV=15 columns. It corresponds to the "spatial" 6D velocity of the end effector. Let's first focus on the 3 first rows, corresponding to the linear velocity. Instant velocity of the original frame:

In [32]:
Jtool3 = Jtool[:3,:]

#### Jacobian as a velocity operator
A first way to understand what is this matrix is to see that as an operator that converts the velocity in the configuration space into the linear velocity of the end effector.

In [33]:
vtool = Jtool3 @ vq # [3, NV] @ [NV]
vtool.shape

(3,)

But in which frame is vtool expressed? The choice in Pinocchio (following algorithmic principles described in [Featherstone 2009]) 
is to express quantities in the local frame by default.

So `vtool` is expressed in the tool frame $F_{tool}$. We should better denote it with its frame. We can compute the velocity in the world frame $F_0$, knowing that $F_{tool}$ is place with a relative rotation $^{o}R_{tool}$:

In [36]:
tool_vtool = vtool
o_vtool = oMtool.rotation @ vtool

In [37]:
tool_Jtool = pin.computeFrameJacobian(robot.model, robot.data, q, IDX_TOOL, pin.LOCAL)
tool_Jtool3 = tool_Jtool[:3,:]

We are using here long variable names. In the code, these explicit notations are maybe to much. It is your choice to use them or not. For sure, you should use similar notations on the paper board when formulating your algorithm, but maybe you prefer lighter variable naming for implementing it.
The tool velocity is easier to interpret in the world frame.

We generalize this notation to the jacobian part dedidcated to linear velocity expressed in the world frame $F_0$:

In [38]:
o_Jtool3 = oMtool.rotation @ tool_Jtool3
# moving the jacobian to the world frame o by applying the referential rotation of the tool (invariant by translation any way to oMtool.translation is not used here.)

To be more precise, relation between jacobian, motion and frame can be as follow:
$$^{tool}J_{tool} \dot{q} = ^{tool}w_{tool} = [^{tool}v_{tool}, ^{tool}\omega_{tool}]$$ 
is the instantaneous solid motion of frame $F_{tool}$ express in itself. 


$^{tool}w_{tool}$ is a twist, an element of the algebra $\mathfrak{se}(3)$. We can interpret $^{tool}v_{tool}$ as the point velocity of the frame $F_{tool}$ origin express in itself and $^{tool}\omega_{tool}$ as the instaneous rotation axis/amplitude.

Then we can express those two vectors in the world origin $F_{0}$ using $^0R_{tool}$. we have: $$[^{0}v_{tool}, ^{0}\omega_{tool}] = [^0R_{tool}\vphantom{.}^{tool}v_{tool}, ^0R_{tool}\vphantom{.}^{tool}\omega_{tool}]$$
the quantities $^{0}v_{tool}$ and $^{0}\omega_{tool}$ are easilly interpretable as the same vector quantities in a different frame.

In [48]:
# Angular velocity - we transform the parameters derivative vq in the config space into a 3D angular velocity vector... in the workspace ... at the tool position , expressed in the tool referential
tool_Omega_tool = Jtool[3:] @ vq # [3, NV] @ [NV]
tool_Omega_tool.shape
o_Omega_tool = oMtool.rotation @ tool_Omega_tool


----------------

:warning: **Note** $[^{0}v_{tool}, ^{0}\omega_{tool}] \neq ^{0}w_{tool}$  expressing the "twist" in the original referential *(differs for the linear velocity part, rotation remains the same)*

However, we can also expres the whole instantaneous motion in the original frame:
$$^{0}w_{tool} = ^{0}J_{tool}\dot{q} = ^{0}X_{tool}\vphantom{.}^{tool}J_{tool} \dot{q}$$
where $^{0}X_{tool}$ is the adjoint operator related to $^{0}R_{tool}, ^{0}T_{tool}$ that allows to change frame for element of $\mathfrak{se}(3)$. We can note that:
$$^{0}w_{tool} = ^{0}X_{tool}[^{tool}v_{tool}, ^{tool}\omega_{tool}] = [^0R_{tool}\vphantom{.}^{tool}v_{tool} + ^0T_{tool} \wedge ^0R_{tool}\vphantom{.}^{tool}\omega_{tool}, ^0R_{tool}\vphantom{.}^{tool}\omega_{tool}]=[^0v_{tool} + ^0T_{tool} \wedge ^{0}\omega_{tool}, ^{0}\omega_{tool}]$$
note here that the angular component of $^{0}w_{tool}$ is $^{0}\omega_{tool}$ but the linear part is not $^0v_{tool}$ but use the Varignon formula instead. It has not an easy interpretation on its own, it is the linear part of the instantaneous motion express in the world frame.

#### Jacobian as a derivative
In the previous section (`Jacobian as a velocity operator`)
- jacobians are operator transforming configuration velocity into Frame instantaneous motion (velocity in $\mathfrak{se}(3)$) 
- and frame manipulation allow to express velocity of the origin or instaneous motion in every other frame.

A second interpretation of is to observe that it is the derivative of the placement following q.


For the three first colums, 
it is the derivative of the vector $^0T_{tool} = (o_{tool} - o_0)$ the tool position in world frame. 

Indeed $^0T_{tool}$ is a function of q: 

**$^0T(q)$, the function is actually the forward kinematic.**

We can take its derivative with respect to q, denoted $\frac{\partial ^0T_{tool}}{\partial q}$.

This derivatives is equal to the Jacobian expressed in the world frame $F_0$: $\frac{\partial ^0T}{\partial q} = \vphantom{.}^0J_{tool}$.

The global jacobian is the same for the whole motion expression using the algebra of the Lie group $SE(3)$

$$^{tool}J_{tool}(q) u = \lim_{t \to 0^+}\frac{^{0}M_{tool}(q \oplus_{\mathcal{C}} tu) \ominus_{SE(3)} \vphantom{.}^{0}M_{tool}(q)}{t}$$

:warning: typo $^{0}J_{tool}(q) * u = \lim_{t \to 0^+}\frac{^{0}M_{tool}(q \oplus_{\mathcal{C}} tu) \ominus_{SE(3)} \vphantom{.}^{0}M_{tool}(q)}{t}$


To be convinced of that, let's check the finite differences. We take a small movement dq, and see that the change in position `o_OT(q+dq)` corresponds to the linear prediction `o_Jtool3*dq`.


In [49]:
# Sample between -0.001 and 0.001
EPS = 1e-4
u = (np.random.rand(robot.model.nv)*2-1)
dq = u*EPS

# q2 = q+dq
q2 = pin.integrate(robot.model,q, dq)                     

# tool position for q -> use forward kinematics before accessing the "placement" of the tool in SE(3).
pin.framesForwardKinematics(robot.model,robot.data,q)
o_M_tool = robot.data.oMf[IDX_TOOL].copy()
o_T_tool = o_M_tool.translation

# tool position for q+dq -> use forward kinematics before accessing the displaced tool "placement" in SE(3).
pin.framesForwardKinematics(robot.model,robot.data,q2)
o_M_tool2 = robot.data.oMf[IDX_TOOL].copy()
o_T_tool2 = o_M_tool2.translation


print('Full jacobian in the tool frame MULTIPLIED by a specific config space vector u!')
print((tool_Jtool @ u)) # not the jacobian 
print(pin.log(o_M_tool.inverse() * o_M_tool2).vector / EPS) # Using the log to make a difference of  2 SE(3) placements to get a velocity in the tangent space se(3)

# tool_Jtool : [6, nv] ...
# tool_Jtool @ u  : [6,]

print('\nOrigin velocity in the world frame')
print((o_Jtool3 @ u))
print(o_M_tool.rotation @ pin.log(o_M_tool.inverse() * o_M_tool2).linear / EPS)
print((o_T_tool2 - o_T_tool)/EPS)

Full jacobian in the tool frame
[ 0.63934072 -0.28195988 -0.30597487  0.08273657  0.64339804 -0.89149463]
[ 0.6393838  -0.28193702 -0.30599051  0.08268802  0.64349494 -0.89146939]

Origin velocity in the world frame
[0.4568761  0.54743394 0.27103297]
[0.45686574 0.54747969 0.2710535 ]
[0.45689278 0.54747222 0.27102301]


#### Frame options in Pinocchio
Most algorithms accept an option to specify in which frame the spatial quantity should be expressed. 

The two basic options are `pin.LOCAL` and `pin.WORLD`.

When related to velocity, *LOCAL* is the linear velocity of the center of the local frame (the TOOL_IDX frame, here) and the angular velocity, both expressed in the local frame. With *WORLD* frame, this is the instantaneous motion expressed in the world frame.

It is also composed of a linear and an angular velocity but remember that the linear velocity is then difficult to interpret.

A last option is given by convenience, which does not respect the mathematics of spatial velocity, but matches the French "torseur cinématique": 
`pin.LOCAL_WORLD_ALIGNED` gives the linear velocity of the center of the local frame and the angular velocity, both expressed in the world frame.

*It is convenient especially when we are interested to consider the linear velocity as the derivative of the position. This is what we did above.*

To recap:
- `pin.LOCAL` gives $^{tool}w_{tool} = [^{tool}v_{tool}, ^{tool}\omega_{tool}]$
- `pin.WORLD` gives $^{0}w_{tool} =\vphantom{.}^{0}X_{tool}\vphantom{.}^{tool}w_{tool}=\left(\begin{array}{c|c} 
  ^0R_{tool} & [^0T_{tool}]_{\times}\vphantom{.}^0R_{tool} \\ 
  \hline 
  0 & ^0R_{tool}
\end{array} 
\right)\vphantom{.}^{0}w_{tool}$
- `pin.LOCAL_WORLD_ALIGNED` gives $[^{0}v_{tool}, ^{0}\omega_{tool}]=\left(
\begin{array}{c|c} 
  ^0R_{tool} & 0 \\ 
  \hline 
  0 & ^0R_{tool}
\end{array} 
\right)\vphantom{.}^{0}w_{tool}$


In [ ]:
# 0wtool and toolwtool
tool_Jtool = pin.computeFrameJacobian(robot.model,robot.data,q,IDX_TOOL, pin.LOCAL)
o_Jtool = pin.computeFrameJacobian(robot.model,robot.data,q,IDX_TOOL, pin.WORLD)
print(o_Jtool @ u)
print(oMtool.action @ (tool_Jtool @ u))

# 0vtool and toolwtool
o_Jtool3 = oMtool.rotation @ tool_Jtool[:3, :]
print((o_Jtool3 @ u))
new_o_Jtool3 = pin.computeFrameJacobian(robot.model,robot.data,q,IDX_TOOL, pin.LOCAL_WORLD_ALIGNED)[:3,:]
print((new_o_Jtool3 @ u))

You may see this video which explain with more illustriations the 3 frame options:  https://youtu.be/MLFtHLTprE4 

## Inverse kinematics for the moving the robot effector
We will first move only the robot end effector, to reach a target defined by a frame F_goal.

In [ ]:
# Goal placement, and integration in the viewer of the goal.
oMgoal = pin.SE3(pin.Quaternion(-0.5, 0.58, -0.39, 0.52).normalized().matrix(),
                np.array([1.2, .4, .7]))
viz.addBox('goal', [.1,.1,.1], [ .1,.1,.5, .6] )
viz.applyConfiguration('goal',oMgoal)

### Position the effector (3d)
It is time to write your first control law. Write a for-loop to iterate along the control cycles of the robot. At each control cycle, you should:
* compute the Jacobian 3D in the world frame `o_Jtool3`
* compute the vector from the tool to the goal, expressed in world frame: o_TG = o_goal - o_tool 
* compute the control law as `vq=pinv(o_Jtool3) * o_TG`
* integrated the velocity vq during DT to get a new configuration q.
You might want to start from the following initial configuration, or from any random one.

`pinv(J)` computes  $J^+$ the Moore Penrose pseudo inverse of $J$.

Precisely, for any $e$, $J^+ e$ is the solution of the linear least square problem:

$\min_x \|Jx - e\|_2^2$

In [ ]:
# Robot initial configuration.
q0 = np.array([ 0.  ,  0.  ,  1.  ,  0.  ,  0.18,  1.37, -0.24, -0.98,  0.98,
                0.  ,  0.  ,  0.  ,  0.  , -0.13,  0.  ,  0.  ,  0.  ,  0.  ])
DT = 1e-2

It is a good idea to store the values of the error between tool and goal o_TG, to plot them later. For that, simply append each o_TG computed at every control cycle in a list.

In [ ]:
q = q0.copy()
herr = [] # Log the value of the error between tool and goal.

for i in range(500):  # Integrate over 2 second of robot life

    # REPLACE
    o_TG = np.zeros(3)    
    q = q0    

    viz.display(q)
    time.sleep(1e-3)

    herr.append(o_TG) 


It is interesting to plot the behavior of the robot. If the error at each iteration has been stored as a list of 3x1 matrices, the following code plots it.

In [ ]:
plt.plot(herr)
plt.xlabel('control cycle (iter)')
plt.ylabel('error (m)');

We can observe that each component of the error converges toward 0 following an exponential trajetory. The convergence is assymptotic. To fasten the convergence, increase the gain of the control law ($v_q = - \lambda J^+ e$), where the gain $\lambda$ has yet been set to 1.

### Place the end effector (6D)
The previous control law brings the center of the effector toward the center of the goal frame. However, it does not control the orientation of the end effector: the axes of the two frames F_tool and F_goal do not converge.
We should now modify the control law to take into account the tool orientation. For that, we compute the error to be the SE(3) log of the displacement from the tool frame F_tool to the goal frame F_goal.

We will use `J` instead of `J3`, and we need to compute  a vector of the generalized difference between the tool frame and the goal frame:
$$^{tool}M_{goal} = \vphantom{.}^{o}M_{tool} \vphantom{.}^{-1} \vphantom{.}^{o}M_{tool}$$
$$^{tool}w_{goal} = \vphantom{.}^{o}M_{tool} \ominus_{SE(3)} \vphantom{.}^{o}M_{tool} = log_{SE(3)}(^{tool}M_{goal})$$
where $^{tool}w_{goal}$ is a spatial vector in the local frame.

In [ ]:
toolMgoal = oMtool.inverse() * oMgoal
tool_w = pin.log(toolMgoal).vector

This error tool_nu is a 6d vector, that can be interpreted as the spatial (6d) velocity that should be applied during 1 second to displace the tool frame F_tool (placed at oMtool) to the goal frame F_goal (placed at oMgoal). This spatial velocity is expressed in the tool frame F_tool. It then corresponds to the 6D jacobian, that is also computed in the same frame F_tool.

Implement a second control law, following the same pattern than the previous control law. At each control cycle, you should:
* compute the displacement between F_tool and F_goal, denoted toolMgoal
* compute the 6D error using the SE(3) log tool_nu
* compute the 6D jacobian tool_Jtool
* compute the control law vq = pinv(J)*nu
* integrate the robot velocity vq during DT to get a new configuration q
* log the error by storing it in a list herr.

In [ ]:
# Your code

The tool frame F_tool converges toward the gooal frame F_goal: the center and the axes are finally aligned. The trajectory of the tool center is not a straight line, as the frame F_tool follows a "straight" line, not in R^3 but in SE(3).
We can also plot the error (assuming that herr is a list of the 6D errors herr).

In [ ]:
plt.subplot(211)
plt.plot([ e[:3] for e in herr])
plt.xlabel('control cycle (iter)')
plt.ylabel('error (m)')
plt.subplot(212)
plt.plot([ e[3:] for e in herr])
plt.xlabel('control cycle (iter)')
plt.ylabel('error (rad)');


### Inverse kinematics for two tasks
We yet controlled the robot with a single task (either the 3d position or the 6d placement errors). Let's see how to take into account a second task. Let's first introduce a second task. 

#### Introducing a second task: control the gaze
The robot has an additional frame named F_gaze, attached to the head and located 40 cm in front of the cameras. The task will be to position (3d) the center of this frame on an object of interest (a red ball).

In [ ]:
robot = loadTiago(addGazeFrame=True)
viz = MeshcatVisualizer(robot)

In [ ]:
IDX_GAZE = robot.model.getFrameId('framegaze')

# Add a small ball as a visual target to be reached by the robot
ball = np.array([ 1.2,0.5,1.1 ])
viz.addSphere('ball', .05, [ .8,.1,.5, .8] )
viz.applyConfiguration('ball', list(ball)+[0,0,0,1])

# Add the box again
oMgoal = pin.SE3(pin.Quaternion(-0.5, 0.58, -0.39, 0.52).normalized().matrix(),
                np.array([1.2, .4, .7]))
viz.addBox('goal', [.1,.1,.1], [ .1,.1,.5, .6] )
viz.applyConfiguration('goal',oMgoal)


In [ ]:
viz.display(q0)
viz.viewer.jupyter_cell()

Controlling this point can be done by achieving a simple variation of the control law for positioning (3d) the robot tool.

In [ ]:
# Your code

#### Performing 2 tasks

We now have two tasks (e1,J1) controlling the tool placement and (e2,J2) controlling the gaze position.

We use the previous technique to compute:
$$vq_1 = J_1^+ v_1^*$$
the optimal (in a least square sense) control for task 1. Then we can add any vector which is in the null space of $J_1$ to perform the second task. We search for $vq = vq_1 + dvq$ where $dvq$ gives an optimal control for task 2.

The orthogonal null space projector of $J_1$ can be computed using the pseudoinverse.
$$P_1 = I_{nq} - J_1^+ J_1$$
Finally, the control law to perform task 1 and task 2 in the null space of task 1 is:

$$vq_2 = vq_1 + (J_2 P_1)^+ ( v_2^* - J_2 vq_1)$$

You can now implement a control law solving the two tasks, i.e positioning the tool while controlling the gaze. Where we use $dvq$ being a solution of the minimisation problem:
$$\min_{x\in Ker(J_1)} \|J_2 (vq_1 + x) - v_2^*\|_2^2$$


In [ ]:
q = q0.copy()
herr = [] # Log the value of the error between tool and goal.
herr2 = [] # Log the value of the error between gaze and ball.
# Your code

In [ ]:
plt.subplot(311)
plt.plot([ e[:3] for e in herr])
plt.xlabel('control cycle (iter)')
plt.ylabel('error (m)')
plt.subplot(312)
plt.plot([ e[3:] for e in herr])
plt.xlabel('control cycle (iter)')
plt.ylabel('error (rad)');
plt.subplot(313)
plt.plot([ e for e in herr2])
plt.xlabel('control cycle (iter)')
plt.ylabel('error (rad)');


## Extension

A third task can be implemented as well by computing the null space of the two first tasks:

In [ ]:
Pgaze = Ptool - pinv(o_Jgaze3 @ Ptool) @ o_Jgaze3 @ Ptool


Load an extra cube in the viewer to figure a table. First control the robot hand to reach an arbitrary point on the table (don't mind for the collision). Then implement a control law to control three tasks:
* the tool frame should be kept on the table (i.e. only the z component of the error matter, select only the 3rd row of the matrix).
* the gaze should be control to reach the position of a ball object positionned on the table.
* the center of the basis frame should reach a given target on the floor. For this task, only the x- and y- component of the task matter, select only the 2 first rows.


In [ ]:
# Your code